name: Code Checker

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  save-file:
    runs-on: self-hosted
    
    name: Print issue title
    steps:
    - run: echo "${{github.event.issue.title}}"
